baseurl = "http://ghstahl.github.io/LearnPingoConsole/"
languageCode = "en-us"
title = "Learn Pingo Console"
pygmentsuseclasses = true
disqusShortname = "learnpingoconsole"
[params]
  googleAnalytics = "UA-65241356-1"
  
[[menu.doctype]]
  name = "Tutorial"
  url = "/tutorial/" 
  weight = 1

[[menu.doctype]]
  name = "Developer"
  identifier ="Developer"
  url = "/developer/"
  weight = 2

