baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Learn Pingo Console"
OpenSourceRepo="https://github.com/ghstahl/PingoConsole"

[[menu.doctype]]
  name = "Tutorial"
  url = "/tutorial/" 
  weight = 1

[[menu.doctype]]
  name = "Developer"
  identifier ="Developer"
  url = "/developer/"
  weight = 2

